// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NullzoneStudiosWebsite.Server;

#nullable disable

namespace NullzoneStudiosWebsite.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260326150744_AddProjects")]
    partial class AddProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.Project", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BannerImageUrl")
                        .HasColumnType("longtext")
                        .HasColumnName("banner_image_url");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("title");

                    b.Property<string>("href")
                        .HasColumnType("longtext")
                        .HasColumnName("href");

                    b.HasKey("ID");

                    b.ToTable("nullzonewebsite_projects");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expires_at");

                    b.Property<string>("FamilyID")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("family_id");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("revoked_at");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token");

                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserID");

                    b.ToTable("nullzonewebsite_refresh_tokens");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_ID");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AccessLevel")
                        .HasColumnType("int")
                        .HasColumnName("access_level");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<DateTime>("LastLoginStamp")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("last_login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("salt");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("ID");

                    b.ToTable("nullzonewebsite_users");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.UserData", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<DateOnly?>("Birthdate")
                        .HasColumnType("date")
                        .HasColumnName("birthdate");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("display_name");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext")
                        .HasColumnName("gender");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("longtext")
                        .HasColumnName("profile_image");

                    b.HasKey("UserID");

                    b.ToTable("nullzonewebsite_user_data");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.UserWorkerData", b =>
                {
                    b.Property<int>("UserID")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("about");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("job_title");

                    b.HasKey("UserID");

                    b.ToTable("nullzonewebsite_user_worker_data");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.RefreshToken", b =>
                {
                    b.HasOne("NullzoneStudiosWebsite.Server.DataModels.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.UserData", b =>
                {
                    b.HasOne("NullzoneStudiosWebsite.Server.DataModels.User", "User")
                        .WithOne("UserData")
                        .HasForeignKey("NullzoneStudiosWebsite.Server.DataModels.UserData", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.UserWorkerData", b =>
                {
                    b.HasOne("NullzoneStudiosWebsite.Server.DataModels.User", "User")
                        .WithOne("UserWorkerData")
                        .HasForeignKey("NullzoneStudiosWebsite.Server.DataModels.UserWorkerData", "UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NullzoneStudiosWebsite.Server.DataModels.User", b =>
                {
                    b.Navigation("RefreshTokens");

                    b.Navigation("UserData")
                        .IsRequired();

                    b.Navigation("UserWorkerData");
                });
#pragma warning restore 612, 618
        }
    }
}
